# Generated by Django 3.2.3 on 2021-06-19 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitemessage',
            name='user',
        ),
    ]
