# Generated by Django 3.2.3 on 2021-06-19 14:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_remove_invitemessage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitemessage',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
