# Generated by Django 3.2.3 on 2021-06-22 17:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_alter_user_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='excluded_receivers',
            field=models.ManyToManyField(blank=True, null=True, related_name='excluded', to=settings.AUTH_USER_MODEL),
        ),
    ]
