# Generated by Django 3.2.3 on 2021-06-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_alter_message_excluded_receivers'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='default_income_type',
            field=models.BooleanField(default=False),
        ),
    ]
