# Generated by Django 3.2.3 on 2021-06-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_transaction_default_income_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='default_income_type',
        ),
        migrations.AddField(
            model_name='paymentitem',
            name='default_income_type',
            field=models.BooleanField(default=False),
        ),
    ]
