# Generated by Django 3.2.3 on 2021-06-27 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0012_message_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='measure_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentitem',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
