# Generated by Django 3.2.3 on 2021-06-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0013_auto_20210627_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactspage',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customabstractuser',
            name='phone_number',
            field=models.CharField(max_length=30),
        ),
    ]
