# Generated by Django 3.2.3 on 2021-06-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0015_auto_20210628_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='paid_sum',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
