# Generated by Django 3.2.3 on 2021-06-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0017_alter_transaction_paid_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='square',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
